import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Notifications from "../components/chatroom/Notifications";
import Options from "../components/chatroom/Options";

import VideoPlayer from "../components/chatroom/VideoPlayer";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>ChatWithme</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen bg-gradient-to-b from-[#951d5d] to-[#7f1685]">
        <div className="flex justify-center py-8">
          <div className="w-[60%] bg-slate-300">
            <h1 className="border-1 text-center font-poppins text-5xl font-bold">
              Video Chat
            </h1>
          </div>
        </div>
        <VideoPlayer />
        <Options>
          <Notifications />
        </Options>
      </div>
    </>
  );
};

export default Home;
